In [ ]:
# Bài 1

import numpy as np

arr1 = np.arange(1, 11)

# Kiểm tra kích thước và kiểu dữ liệu
shape1 = arr1.shape
dtype1 = arr1.dtype
print("Mảng 1 chiều:", arr1)
print("Shape:", shape1)
print("Dtype:", dtype1)

# Chuyển đổi sang float
arr1_float = arr1.astype(np.float32)
print("Mảng 1 chiều kiểu float:", arr1_float)
print("Dtype sau chuyển đổi:", arr1_float.dtype)

arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Kiểm tra kích thước và kiểu dữ liệu
shape2 = arr2.shape
dtype2 = arr2.dtype
print("Mảng 2 chiều:\n", arr2)
print("Shape:", shape2)
print("Dtype:", dtype2)

# Chuyển đổi sang float
arr2_float = arr2.astype(np.float32)
print("Mảng 2 chiều kiểu float:\n", arr2_float)
print("Dtype sau chuyển đổi:", arr2_float.dtype)


Mảng 1 chiều: [ 1  2  3  4  5  6  7  8  9 10]
Shape: (10,)
Dtype: int64
Mảng 1 chiều kiểu float: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
Dtype sau chuyển đổi: float32
-----
Mảng 2 chiều:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Dtype: int64
Mảng 2 chiều kiểu float:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Dtype sau chuyển đổi: float32


In [3]:
# Bài 2

import numpy as np

arr1 = np.arange(1, 11)

first_elem = arr1[0] 
last_elem = arr1[-1]   
middle_elem = arr1[5] 

sliced_arr = arr1[2:6]

arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

row2 = arr2[1]

col3 = arr2[:, 2]

print("arr1 =", arr1)
print("arr2 =\n", arr2)
print()

print("Phần tử đầu tiên =", first_elem)
print("Phần tử cuối cùng =", last_elem)
print("Phần tử giữa =", middle_elem)

print("Phần tử từ vị trí 2 đến 5 =", sliced_arr.tolist())
print("hàng thứ 2 =", row2.tolist())
print("cột thứ 3 =", col3.tolist())


arr1 = [ 1  2  3  4  5  6  7  8  9 10]
arr2 =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Phần tử đầu tiên = 1
Phần tử cuối cùng = 10
Phần tử giữa = 6
Phần tử từ vị trí 2 đến 5 = [3, 4, 5, 6]
hàng thứ 2 = [4, 5, 6]
cột thứ 3 = [3, 6, 9]


In [4]:
# Bài 3

import numpy as np

arr = np.array([
    [88, 35, 62],
    [11, 98, 34],
    [64, 24, 48]
])

print(arr)

min_val = np.min(arr)
max_val = np.max(arr)
sum_val = np.sum(arr)
mean_val = np.mean(arr)
std_val = np.std(arr)

print("Min:", min_val)
print("Max:", max_val)
print("Sum:", sum_val)
print("Mean:", mean_val)
print("STD:", std_val)

# Hàng
sum_col = np.sum(arr, axis=0)
mean_col = np.mean(arr, axis=0)

print("\nSumOfColumn:", sum_col)
print("MeanOfColumn:", mean_col)

# Cột
sum_row = np.sum(arr, axis=1)
mean_row = np.mean(arr, axis=1)

print("\nSumOfRow:", sum_row)
print("MeanOfRow:", mean_row)

[[88 35 62]
 [11 98 34]
 [64 24 48]]
Min: 11
Max: 98
Sum: 464
Mean: 51.55555555555556
STD: 27.38252123409754

SumOfColumn: [163 157 144]
MeanOfColumn: [54.33333333 52.33333333 48.        ]

SumOfRow: [185 143 136]
MeanOfRow: [61.66666667 47.66666667 45.33333333]


In [ ]:
# Bài 4

import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([10, 20, 30])

add_result = A + B

sub_result = A - B

print("\nKết quả phép cộng A + B:\n", add_result)
print("\nKết quả phép trừ A - B:\n", sub_result)


Kết quả phép cộng A + B:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]

Kết quả phép trừ A - B:
 [[ -9 -18 -27]
 [ -6 -15 -24]
 [ -3 -12 -21]]


In [ ]:
# Bài 5

import numpy as np
import time

arr1 = np.random.randint(1, 21, size=10)

squared = arr1 ** 2
sqrt_val = np.sqrt(arr1)

print("Bình phương:", squared)
print("Căn bậc hai:", sqrt_val)

added = np.add(arr1, 5)
multiplied = np.multiply(arr1, 3)
sqrt_ufunc = np.sqrt(arr1)

print("Kết quả dùng ufunc:")
print("np.add(arr1, 5):", added)
print("np.multiply(arr1, 3):", multiplied)
print("np.sqrt(arr1):", sqrt_ufunc)

arr2 = np.random.randint(1, 100, size=(1000, 1000))

start_vec = time.time()
vec_result = arr2 * 2
end_vec = time.time()

start_loop = time.time()
loop_result = np.zeros_like(arr2)
for i in range(arr2.shape[0]):
    for j in range(arr2.shape[1]):
        loop_result[i, j] = arr2[i, j] * 2
end_loop = time.time()

print("So sánh thời gian thực thi:")
print("Vectorization:", end_vec - start_vec, "giây")
print("Vòng lặp:", end_loop - start_loop, "giây")


Mảng 1D: [15  9 13  6 12  7 13  9 17  3]

Bình phương: [225  81 169  36 144  49 169  81 289   9]
Căn bậc hai: [3.87298335 3.         3.60555128 2.44948974 3.46410162 2.64575131
 3.60555128 3.         4.12310563 1.73205081]

Kết quả dùng ufunc:
np.add(arr1, 5): [20 14 18 11 17 12 18 14 22  8]
np.multiply(arr1, 3): [45 27 39 18 36 21 39 27 51  9]
np.sqrt(arr1): [3.87298335 3.         3.60555128 2.44948974 3.46410162 2.64575131
 3.60555128 3.         4.12310563 1.73205081]
So sánh thời gian thực thi:
Vectorization: 0.0020017623901367188 giây
Vòng lặp: 0.35596585273742676 giây


In [7]:
# Bài 6

import numpy as np

arr = np.array([
    [3, 7, 4, 5],
    [3, 5, 2, 4],
    [6, 3, 9, 7],
    [4, 8, 3, 5]
])

# Tính theo cột (axis=0)
sum_col = np.sum(arr, axis=0)
mean_col = np.mean(arr, axis=0)
std_col = np.std(arr, axis=0)

print("\nTổng theo cột (axis=0):", sum_col)
print("Trung bình theo cột (axis=0):", mean_col)
print("Độ lệch chuẩn theo cột (axis=0):", std_col)

# Tính theo hàng (axis=1)
sum_row = np.sum(arr, axis=1)
mean_row = np.mean(arr, axis=1)
std_row = np.std(arr, axis=1)

print("\nTổng theo hàng (axis=1):", sum_row)
print("Trung bình theo hàng (axis=1):", mean_row)
print("Độ lệch chuẩn theo hàng (axis=1):", std_row)


Tổng theo cột (axis=0): [16 23 18 21]
Trung bình theo cột (axis=0): [4.   5.75 4.5  5.25]
Độ lệch chuẩn theo cột (axis=0): [1.22474487 1.92028644 2.6925824  1.08972474]

Tổng theo hàng (axis=1): [19 14 25 20]
Trung bình theo hàng (axis=1): [4.75 3.5  6.25 5.  ]
Độ lệch chuẩn theo hàng (axis=1): [1.47901995 1.11803399 2.16506351 1.87082869]


In [8]:
# Bài 7

import numpy as np
import time

A = np.array([
    [8, 12, 14, 6, 4],
    [18, 13, 2, 2, 12],
    [6, 18, 5, 10, 10],
    [9, 2, 4, 12, 12],
    [2, 3, 2, 17, 3]
])

B = np.array([10, 20, 30, 40, 50])

# Broadcasting
add_bc = A + B
sub_bc = A - B

print("\nKết quả cộng (broadcasting):\n", add_bc)
print("\nKết quả trừ (broadcasting):\n", sub_bc)

# Ufunc
sqrt_uf = np.sqrt(A)
add5_uf = np.add(A, 5)

print("\nKết quả căn bậc hai (ufunc):\n", sqrt_uf)
print("\nKết quả cộng 5 vào mảng (ufunc):\n", add5_uf)

# Đo tốc độ vòng lặp thủ công
start_loop = time.time()
loop_result = np.zeros_like(A)
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        loop_result[i, j] = A[i, j] + 5
end_loop = time.time()

print("\nThời gian thực thi vòng lặp thủ công:",
      round(end_loop - start_loop, 6), "giây")



Kết quả cộng (broadcasting):
 [[18 32 44 46 54]
 [28 33 32 42 62]
 [16 38 35 50 60]
 [19 22 34 52 62]
 [12 23 32 57 53]]

Kết quả trừ (broadcasting):
 [[ -2  -8 -16 -34 -46]
 [  8  -7 -28 -38 -38]
 [ -4  -2 -25 -30 -40]
 [ -1 -18 -26 -28 -38]
 [ -8 -17 -28 -23 -47]]

Kết quả căn bậc hai (ufunc):
 [[2.82842712 3.46410162 3.74165739 2.44948974 2.        ]
 [4.24264069 3.60555128 1.41421356 1.41421356 3.46410162]
 [2.44948974 4.24264069 2.23606798 3.16227766 3.16227766]
 [3.         1.41421356 2.         3.46410162 3.46410162]
 [1.41421356 1.73205081 1.41421356 4.12310563 1.73205081]]

Kết quả cộng 5 vào mảng (ufunc):
 [[13 17 19 11  9]
 [23 18  7  7 17]
 [11 23 10 15 15]
 [14  7  9 17 17]
 [ 7  8  7 22  8]]

Thời gian thực thi vòng lặp thủ công: 0.0 giây


In [9]:
# Bài 8

import numpy as np

A = np.random.randint(1, 10, (3, 3))
print("Ma trận gốc:\n", A)

A_inv = np.linalg.inv(A)
print("\nMa trận nghịch đảo:\n", A_inv)

# 3. Tính giá trị riêng và véc tơ riêng
eig_vals, eig_vecs = np.linalg.eig(A)

print("\nGiá trị riêng của ma trận:")
print(eig_vals)

print("\nVéc tơ riêng tương ứng:")
print(eig_vecs)

# 4. So sánh A ⋅ A_inv ≈ I
identity_check = A @ A_inv
print("\nA nhân với A_inv (≈ ma trận đơn vị):")
print(identity_check)


Ma trận gốc:
 [[2 6 5]
 [3 4 8]
 [1 2 1]]

Ma trận nghịch đảo:
 [[-0.75    0.25    1.75  ]
 [ 0.3125 -0.1875 -0.0625]
 [ 0.125   0.125  -0.625 ]]

Giá trị riêng của ma trận:
[ 9.73645006 -0.88996743 -1.84648263]

Véc tơ riêng tương ứng:
[[-0.68618598 -0.93418982  0.75304481]
 [-0.68805934  0.3220945  -0.63284205]
 [-0.23605751  0.15344223  0.1800957 ]]

A nhân với A_inv (≈ ma trận đơn vị):
[[ 1.00000000e+00 -6.93889390e-17  4.44089210e-16]
 [-2.22044605e-16  1.00000000e+00  0.00000000e+00]
 [-1.11022302e-16 -1.38777878e-17  1.00000000e+00]]
