In [6]:
# Bài 1

lst = [1, 2, 3, 2, 5, 1, 7, 9, 9, 4]

even_position_elements = lst[::2]

tuple_from_list = tuple(lst)

dict_from_list = {i: v for i, v in enumerate(lst)}

set_from_list = set(lst)

num_duplicates = len(lst) - len(set_from_list)

print("List ban đầu:", lst)
print("Các vị trí chẵn:", even_position_elements)
print("Tuple:", tuple_from_list)
print("Dict:", dict_from_list)
print("Set:", set_from_list)
print("Số phần tử bị loại trùng:", num_duplicates)


List ban đầu: [1, 2, 3, 2, 5, 1, 7, 9, 9, 4]
Các vị trí chẵn: [1, 3, 5, 7, 9]
Tuple: (1, 2, 3, 2, 5, 1, 7, 9, 9, 4)
Dict: {0: 1, 1: 2, 2: 3, 3: 2, 4: 5, 5: 1, 6: 7, 7: 9, 8: 9, 9: 4}
Set: {1, 2, 3, 4, 5, 7, 9}
Số phần tử bị loại trùng: 3


In [7]:
# Bài 2

import json

with open('data.txt', 'w', encoding='utf-8') as f:
    f.writelines([
        "Xin chào!\n",
        "Đây là file dữ liệu.\n",
        "Python rất hữu ích.\n",
        "Viết file rất đơn giản.\n",
        "Hoàn thành yêu cầu!\n"
    ])

print("Nội dung file data.txt:")
with open('data.txt', 'r', encoding='utf-8') as f:
    for line in f:
        print(line.strip())

student = {
    "name": "An",
    "age": 20,
    "scores": [8, 9, 7]
}

with open('student.json', 'w', encoding='utf-8') as f:
    json.dump(student, f, ensure_ascii=False, indent=2)

with open('student.json', 'r', encoding='utf-8') as f:
    data = json.load(f)
    print("\nJSON đọc từ file:", data)


Nội dung file data.txt:
Xin chào!
Đây là file dữ liệu.
Python rất hữu ích.
Viết file rất đơn giản.
Hoàn thành yêu cầu!

JSON đọc từ file: {'name': 'An', 'age': 20, 'scores': [8, 9, 7]}


In [8]:
# Bài 3

import numpy as np

arr = np.arange(12).reshape(3, 4)

row_2 = arr[1, :]

col_3 = arr[:, 2]

submatrix = arr[1:3, 2:4]

arr_float64 = arr.astype(np.float64)

print("Mảng 3x4:\n", arr)
print("Hàng 2:", row_2)
print("Cột 3:", col_3)
print("Submatrix:\n", submatrix)
print("Dtype mới:", arr_float64.dtype)


Mảng 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Hàng 2: [4 5 6 7]
Cột 3: [ 2  6 10]
Submatrix:
 [[ 6  7]
 [10 11]]
Dtype mới: float64


In [9]:
# Bài 4

import pandas as pd

score_series = pd.Series([7.5, 8.0, 6.5, 9.0, 8.5])

name = ['An', 'Bình', 'Châu', 'Dũng', 'Hà']
age = [20, 21, 22, 20, 23]
score = [7.5, 8.0, 6.5, 9.0, 8.5]

df = pd.DataFrame({'name': name, 'age': age, 'score': score})

df.info()
print(df.describe())

filtered_students = df[df['score'] >= 8]
print("Sinh viên >= 8 điểm:")
print(filtered_students)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   name    5 non-null      object 
 1   age     5 non-null      int64  
 2   score   5 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 248.0+ bytes
            age     score
count   5.00000  5.000000
mean   21.20000  7.900000
std     1.30384  0.961769
min    20.00000  6.500000
25%    20.00000  7.500000
50%    21.00000  8.000000
75%    22.00000  8.500000
max    23.00000  9.000000
Sinh viên >= 8 điểm:
   name  age  score
1  Bình   21    8.0
3  Dũng   20    9.0
4    Hà   23    8.5


In [1]:
# Bài 5

import pandas as pd

students = pd.DataFrame({
    'id': [1, 2, 3],
    'name': ['An', 'Binh', 'Chau']
})
students.to_csv('students.csv', index=False)

scores = pd.DataFrame({
    'id': [1, 2, 3],
    'score': [8, 9, 7]
})
scores.to_csv('scores.csv', index=False)

df_students = pd.read_csv('students.csv')
df_scores = pd.read_csv('scores.csv')

df = pd.merge(df_students, df_scores, on='id')

report = df.groupby(['id', 'name'])['score'].agg(
    score_min='min',
    score_max='max',
    score_mean='mean'
).reset_index()

report.to_csv('report.csv', index=False)

print(report)


   id  name  score_min  score_max  score_mean
0   1    An          8          8         8.0
1   2  Binh          9          9         9.0
2   3  Chau          7          7         7.0


In [3]:
# Bài 6

import numpy as np

a = np.array([[1], [2], [3], [4]])
b = np.array([[10, 20, 30, 40, 50]])

result = a * b

result_sqrt = np.sqrt(result)
result_log = np.log(result)

min_axis1 = np.min(result, axis=1)
max_axis1 = np.max(result, axis=1)
mean_axis1 = np.mean(result, axis=1)
std_axis1 = np.std(result, axis=1)

print("Kết quả phép nhân:\n", result)
print("Căn bậc hai:\n", result_sqrt)
print("Logarit tự nhiên:\n", result_log)
print("Min theo axis 1:", min_axis1)
print("Max theo axis 1:", max_axis1)
print("Mean theo axis 1:", mean_axis1)
print("Std theo axis 1:", std_axis1)



Kết quả phép nhân:
 [[ 10  20  30  40  50]
 [ 20  40  60  80 100]
 [ 30  60  90 120 150]
 [ 40  80 120 160 200]]
Căn bậc hai:
 [[ 3.16227766  4.47213595  5.47722558  6.32455532  7.07106781]
 [ 4.47213595  6.32455532  7.74596669  8.94427191 10.        ]
 [ 5.47722558  7.74596669  9.48683298 10.95445115 12.24744871]
 [ 6.32455532  8.94427191 10.95445115 12.64911064 14.14213562]]
Logarit tự nhiên:
 [[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]
 [2.99573227 3.68887945 4.09434456 4.38202663 4.60517019]
 [3.40119738 4.09434456 4.49980967 4.78749174 5.01063529]
 [3.68887945 4.38202663 4.78749174 5.07517382 5.29831737]]
Min theo axis 1: [10 20 30 40]
Max theo axis 1: [ 50 100 150 200]
Mean theo axis 1: [ 30.  60.  90. 120.]
Std theo axis 1: [14.14213562 28.28427125 42.42640687 56.56854249]


In [4]:
# Bài 7

import pandas as pd
import numpy as np

data = {
    'name': ['An', 'Bình', 'Châu', 'Dũng'],
    'age': [20, np.nan, 22, 21],
    'score': [8.5, np.nan, 7.0, 9.0],
    'city': ['Hà Nội', 'HCM', np.nan, 'Hà Nội']
}

df = pd.DataFrame(data)

print(df.isna())
print("Tổng số giá trị thiếu:", df.isna().sum())

df['age'] = df['age'].fillna(df['age'].mean())
df['score'] = df['score'].fillna(df['score'].median())
df['city'] = df['city'].fillna('Unknown')

print("age_cleaned =", df['age'].tolist())
print("score_cleaned =", df['score'].tolist())
print("city_cleaned =", df['city'].tolist())

df['city'] = df['city'].astype('category')
print("city dtype:", df['city'].dtype)
print("city categories:", df['city'].cat.categories.tolist())

def score_level(val):
    if val >= 8.5:
        return 'Good'
    elif val >= 7.0:
        return 'Average'
    else:
        return 'Bad'

df['score_level'] = df['score'].apply(score_level)
print("score_level =", df['score_level'].tolist())

df['age_normalized'] = (df['age'] - df['age'].mean()) / df['age'].std()
print("age_normalized =", df['age_normalized'].tolist())


    name    age  score   city
0  False  False  False  False
1  False   True   True  False
2  False  False  False   True
3  False  False  False  False
Tổng số giá trị thiếu: name     0
age      1
score    1
city     1
dtype: int64
age_cleaned = [20.0, 21.0, 22.0, 21.0]
score_cleaned = [8.5, 8.5, 7.0, 9.0]
city_cleaned = ['Hà Nội', 'HCM', 'Unknown', 'Hà Nội']
city dtype: category
city categories: ['HCM', 'Hà Nội', 'Unknown']
score_level = ['Good', 'Good', 'Average', 'Good']
age_normalized = [-1.224744871391589, 0.0, 1.224744871391589, 0.0]


In [ ]:
# Bài 8

import json
import pandas as pd
from pathlib import Path
from datetime import datetime

logs_dir = Path('logs')
json_files = list(logs_dir.glob('*.json'))

print(f"Tìm thấy {len(json_files)} file JSON:")
for file in json_files:
    print(f"  - {file.name}")

all_logs = []

for file_path in json_files:
    filename = file_path.stem 
    date_str = filename.replace('log_', '') 
    try:
        log_date = datetime.strptime(date_str, '%Y-%m-%d').date()
        with open(file_path, 'r', encoding='utf-8') as f:
            log = json.load(f)
        if isinstance(log, dict):
            log = [log]
        for entry in log:
            entry['date'] = log_date
            all_logs.append(entry)
    except Exception as e:
        print(f"Lỗi với file {file_path.name}: {e}")

df = pd.DataFrame(all_logs)
print("DataFrame từ tất cả file log:")
print(df)

daily_summary = df.groupby('date')['duration'].sum().reset_index()
daily_summary.columns = ['date', 'total_duration']

print("Tổng duration theo ngày:")
print(daily_summary)

daily_summary.to_csv('daily_report.csv', index=False)


Tìm thấy 3 file JSON:
  - log_2025-01-01.json
  - log_2025-01-02.json
  - log_2025-01-03.json
DataFrame từ tất cả file log:
  user action  duration        date
0    A  login         5  2025-01-01
1    A  login         5  2025-01-02
2    A  login         5  2025-01-03
Tổng duration theo ngày:
         date  total_duration
0  2025-01-01               5
1  2025-01-02               5
2  2025-01-03               5
Đã xuất file daily_report.csv
